name: 🦊 Java CI with Gradle [UBUNTU] Selenium Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: 'all_tests'
        type: choice
        options:
          - 'all_tests'
          - 'api'
          - 'smoky'
          - 'regression'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ✅ ⚙️ Install Java version "17"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'  

      - name: ❎ ⌛️ Check Java version
        run: java -version

      - name: ❎ ⌛️ Check JVM version
        run: echo $JAVA_HOME

      - name: ❎ ⌛️ Check Java Core version
        run: javac -version

      # Устанавливаем Gradle 8.13
      - name: ✅ ⚙️ Install Gradle 8.13
        run: |
          wget https://services.gradle.org/distributions/gradle-8.13-bin.zip
          unzip gradle-8.13-bin.zip
          sudo mv gradle-8.13 /opt/gradle
          echo "/opt/gradle/bin" >> $GITHUB_PATH
          gradle --version

      - name: 🗑️ Remove old Chromedriver
        run: |
          sudo rm -f /usr/local/bin/chromedriver
          sudo rm -rf /usr/bin/chromedriver

      - name: ✅ 🚿 Clean Gradle build
        run: gradle clean

      - name: ✅ 📂 List Directories before tests
        if: always()
        run: ls -R

      - name: ▶️ 🐞 Run tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" gradle clean ${{ github.event.inputs.deployment_target != 'all_tests' && github.event.inputs.deployment_target || '' }} build > build.log 2>&1 || true
        if: github.event_name == 'workflow_dispatch'

      - name: ✅ 📂 List Directories after tests
        if: always()
        run: ls -R

      - name: ✅ 📦 Archive [Gradle build log]
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gradle-build-log.zip
          path: build.log

      - name: ✅ 📦 Archive [Test results]
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gradle-results.zip
          path: build/reports/tests/*

#      - name: ✅ 📦 Archive [Test attachments]
#        uses: actions/upload-artifact@v4
#        if: always()
#        with:
#          name: test-attachments.zip
#          path: target/*

#      - name: ✅ 📦 Archive [Cucumber Report]
#        uses: actions/upload-artifact@v4
#        if: always()
#        with:
#          name: cucumber-report.zip
#          path: target/cucumber-reports.html
